---
image: node

pages:
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - ./.npm/
    policy: pull-push
  stage: deploy
  script:
    - npm ci --cache ./.npm/ --prefer-offline
    - make
  artifacts:
    paths:
      - public
  only:
    - master
