---
image: node

pages:
  cache: &global_cache
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
      - public/
      - vendor/
    policy: pull-push
  stage: deploy
  script:
    - make
  artifacts:
    paths:
      - public
  only:
    - master
